channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.5.0
  - aiohttp=3.11.13
  - aiosignal=1.3.2
  - alsa-lib=1.2.13
  - antlr-python-runtime=4.9.3
  - aom=3.6.1
  - async-timeout=5.0.1
  - attr=2.5.1
  - attrs=25.1.0
  - aws-c-auth=0.7.22
  - aws-c-cal=0.6.15
  - aws-c-common=0.9.23
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.2
  - aws-c-io=0.14.9
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.10
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.12
  - aws-sdk-cpp=1.11.329
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - black=25.1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.1.31
  - cairo=1.18.2
  - certifi=2025.1.31
  - cffi=1.17.1
  - cfgv=3.3.1
  - chardet=5.2.0
  - charset-normalizer=3.4.1
  - click=8.1.8
  - colorama=0.4.6
  - contourpy=1.3.1
  - cpython=3.10.16
  - cryptography=44.0.2
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.6.77
  - cuda-runtime=12.1.0
  - cuda-version=12.6
  - cudnn=8.9.7.29
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - datasets=3.3.2
  - dbus=1.13.6
  - dill=0.3.8
  - distlib=0.3.9
  - double-conversion=3.3.0
  - einops=0.8.1
  - expat=2.6.4
  - ffmpeg=4.4.2
  - filelock=3.16.1
  - flake8=7.1.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.55.3
  - freetype=2.12.1
  - freetype-py=2.3.0
  - frozenlist=1.5.0
  - fsspec=2024.12.0
  - gettext=0.23.1
  - gettext-tools=0.23.1
  - gflags=2.2.2
  - giflib=5.2.2
  - gitdb=4.0.12
  - gitpython=3.1.44
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gnutls=3.7.9
  - graphite2=1.3.13
  - greenlet=3.1.1
  - h2=4.1.0
  - harfbuzz=10.2.0
  - hpack=4.0.0
  - huggingface_hub=0.29.1
  - hyperframe=6.0.1
  - icu=75.1
  - identify=2.6.5
  - idna=3.10
  - isort=6.0.1
  - jinja2=3.1.5
  - joblib=1.4.2
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240116.2
  - libarrow=16.1.0
  - libarrow-acero=16.1.0
  - libarrow-dataset=16.1.0
  - libarrow-substrait=16.1.0
  - libasprintf=0.23.1
  - libasprintf-devel=0.23.1
  - libblas=3.9.0
  - libboost=1.86.0
  - libboost-python=1.86.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.71
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.7
  - libclang13=19.1.7
  - libcrc32c=1.1.2
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.11.1.6
  - libcups=2.3.3
  - libcurand=10.3.7.77
  - libcurl=8.12.1
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.23
  - libdrm=2.4.124
  - libedit=3.1.20240808
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt-lib=1.11.0
  - libgettextpo=0.23.1
  - libgettextpo-devel=0.23.1
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglib=2.82.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgoogle-cloud=2.25.0
  - libgoogle-cloud-storage=2.25.0
  - libgpg-error=1.51
  - libgrpc=1.62.2
  - libhwloc=2.11.2
  - libiconv=1.17
  - libidn2=2.3.7
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm19=19.1.7
  - liblzma=5.6.3
  - liblzma-devel=5.6.3
  - libmagma=2.8.0
  - libmagma_sparse=2.8.0
  - libnghttp2=1.64.0
  - libnl=3.11.0
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libntlm=1.8
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libopenblas=0.3.29
  - libopengl=1.7.0
  - libopentelemetry-cpp=1.16.1
  - libopentelemetry-cpp-headers=1.16.1
  - libparquet=16.1.0
  - libpciaccess=0.18
  - libpng=1.6.45
  - libpq=17.4
  - libprotobuf=4.25.3
  - librdkit=2024.09.6
  - libre2-11=2023.09.01
  - libsqlite=3.48.0
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=256.9
  - libtasn1=4.20.0
  - libthrift=0.19.0
  - libtiff=4.7.0
  - libtorch=2.4.0
  - libudev1=257.2
  - libunistring=0.9.10
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libuv=1.50.0
  - libva=2.22.0
  - libvpx=1.13.1
  - libwebp=1.5.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.13.5
  - libxslt=1.1.39
  - libzlib=1.3.1
  - llvm-openmp=19.1.7
  - lz4-c=1.9.4
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib=3.10.1
  - matplotlib-base=3.10.1
  - mccabe=0.7.0
  - mdurl=0.1.2
  - mkl=2023.2.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.1.0
  - multiprocess=0.70.16
  - munkres=1.1.4
  - mypy=1.15.0
  - mypy_extensions=1.0.0
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - nccl=2.25.1.1
  - ncurses=6.5
  - nettle=3.9.1
  - networkx=3.4.2
  - nlohmann_json=3.11.3
  - nodeenv=1.9.1
  - numpy=2.2.3
  - ocl-icd=2.3.2
  - omegaconf=2.3.0
  - openbabel=3.1.1
  - opencl-headers=2024.10.24
  - openh264=2.3.1
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.4.1
  - optree=0.14.1
  - orc=2.0.1
  - p11-kit=0.24.1
  - packaging=24.2
  - pandas=2.2.3
  - pathspec=0.12.1
  - patsy=1.0.1
  - pcre2=10.44
  - pillow=11.1.0
  - pip=24.3.1
  - pixman=0.44.2
  - platformdirs=4.3.6
  - pre-commit=4.1.0
  - prometheus-cpp=1.2.4
  - propcache=0.2.1
  - psutil=6.1.1
  - pthread-stubs=0.4
  - pyarrow=16.1.0
  - pyarrow-core=16.1.0
  - pybind11=2.13.6
  - pybind11-global=2.13.6
  - pycairo=1.27.0
  - pycodestyle=2.12.1
  - pycparser=2.22
  - pyflakes=3.2.0
  - pygments=2.19.1
  - pyparsing=3.2.1
  - pyside6=6.8.1
  - pysocks=1.7.1
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python-tzdata=2024.2
  - python-xxhash=3.5.0
  - python_abi=3.10
  - pytorch=2.4.0
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - qhull=2020.2
  - qt6-main=6.8.1
  - rdkit=2024.09.6
  - rdma-core=55.0
  - re2=2023.09.01
  - readline=8.2
  - regex=2024.11.6
  - reportlab=4.2.5
  - requests=2.32.3
  - rich=13.9.4
  - rlpycairo=0.2.0
  - s2n=1.4.16
  - safetensors=0.5.3
  - scikit-learn=1.6.1
  - scipy=1.15.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=75.8.0
  - six=1.17.0
  - sleef=3.8
  - smmap=5.0.0
  - snappy=1.2.1
  - sqlalchemy=2.0.37
  - statsmodels=0.14.4
  - svt-av1=1.4.1
  - sympy=1.13.3
  - tbb=2021.13.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tomli=2.2.1
  - torchaudio=2.4.0
  - torchvision=0.19.0
  - tornado=6.4.2
  - tqdm=4.67.1
  - types-pyyaml=6.0.12.20241230
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - ukkonen=1.0.1
  - unicodedata2=16.0.0
  - urllib3=2.3.0
  - virtualenv=20.29.1
  - wayland=1.23.1
  - wayland-protocols=1.41
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.43
  - xlrd=2.0.1
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xxhash=0.8.3
  - xz=5.6.3
  - xz-gpl-tools=5.6.3
  - xz-tools=5.6.3
  - yaml=0.2.5
  - yarl=1.18.3
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - accelerate==1.4.0
      - huggingface-hub==0.29.2
      - synllama==0.1.0
      - tokenizers==0.19.1
      - transformers==4.44.2